version: "3.9"
name: cbrn-spread
services:
  ui:
    build: .
    image: wirries/cbrn-spread:v0.1.0-alpha4
    ports:
      - "3000:3000"
    environment:
      - CBRN_MONGO=db:27017
      # - CBRN_SSL_CERT=/import/data/cert.pem
      # - CBRN_SSL_KEY=/import/data/key.pem
      - CBRN_LOG_LEVEL=info
      - CBRN_TIME_LOG=true
      - HOST=localhost
    depends_on:
      - db
    # volumes:
    #   - ./config:/import/data
  db:
    image: "mongo:4.2.21"
    ports:
      - "27017:27017"
    # volumes:
    #   - ./config/db:/data/db
